"""Add multi-tenancy

Revision ID: 4e1004a142f2
Revises: 4529014d0a85
Create Date: 2026-08-13 21:54:23.530325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1004a142f2'
down_revision: Union[str, Sequence[str], None] = '4529014d0a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtor', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'debtor', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    op.drop_constraint(None, 'debtor', type_='foreignkey')
    op.drop_column('debtor', 'user_id')
    # ### end Alembic commands ###
