"""baseline migration for tables that only ever existed via create_all()

document_client, email_template, pending_subscriptions, document_request,
sweep_run, and processed_stripe_events were never captured by any Alembic
migration — they only exist in production because
Base.metadata.create_all() ran unconditionally on every app startup
(src/app.py's lifespan), which silently created them the first time each
model was added. This closes that gap: it's a from-scratch CREATE TABLE
for each, generated by diffing the actual current models against the
live production database (so this is confirmed accurate, not a guess),
with IF NOT EXISTS guards since production already has them and must not
error when this runs there.

After this, src/app.py no longer calls create_all() in production (see
that commit) — every table a fresh database needs is now captured here.

Revision ID: a225ef8d6e70
Revises: f9a0b1c2d3e4
Create Date: 2026-10-06 11:22:26.823639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a225ef8d6e70'
down_revision: Union[str, Sequence[str], None] = 'f9a0b1c2d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # IF NOT EXISTS: production already has all six tables (created by
    # create_all()); this migration's job is just to bring Alembic's
    # tracked history in line with that reality, not to recreate them.
    op.execute("""
        CREATE TABLE IF NOT EXISTS document_client (
            id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL,
            name VARCHAR NOT NULL,
            email VARCHAR NOT NULL,
            phone VARCHAR,
            created_at TIMESTAMP,
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS email_template (
            id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL,
            template_type VARCHAR NOT NULL,
            subject VARCHAR NOT NULL,
            body TEXT NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS pending_subscriptions (
            id VARCHAR NOT NULL,
            email VARCHAR NOT NULL,
            plan VARCHAR NOT NULL,
            chases_limit INTEGER NOT NULL,
            stripe_customer_id VARCHAR,
            stripe_subscription_id VARCHAR,
            created_at TIMESTAMP WITH TIME ZONE,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_pending_subscriptions_email ON pending_subscriptions (email)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS document_request (
            id VARCHAR NOT NULL,
            user_id VARCHAR NOT NULL,
            client_id VARCHAR NOT NULL,
            title VARCHAR NOT NULL,
            description TEXT,
            due_date DATE NOT NULL,
            status VARCHAR NOT NULL,
            upload_token VARCHAR NOT NULL,
            uploaded_file_name VARCHAR,
            uploaded_at TIMESTAMP WITH TIME ZONE,
            last_reminder_sent TIMESTAMP WITH TIME ZONE,
            escalation_tier VARCHAR NOT NULL,
            escalation_started_at TIMESTAMP WITH TIME ZONE,
            sms_sent_count INTEGER NOT NULL,
            voice_call_count INTEGER NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL,
            stored_file_name VARCHAR,
            PRIMARY KEY (id),
            UNIQUE (upload_token),
            FOREIGN KEY(client_id) REFERENCES document_client (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS sweep_run (
            id VARCHAR NOT NULL,
            last_run_date DATE NOT NULL,
            PRIMARY KEY (id)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS processed_stripe_events (
            event_id VARCHAR NOT NULL,
            event_type VARCHAR NOT NULL,
            processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
            PRIMARY KEY (event_id)
        )
    """)


def downgrade() -> None:
    op.drop_table('processed_stripe_events')
    op.drop_table('sweep_run')
    op.drop_table('document_request')
    op.drop_index('ix_pending_subscriptions_email', table_name='pending_subscriptions')
    op.drop_table('pending_subscriptions')
    op.drop_table('email_template')
    op.drop_table('document_client')
